services:
  scoreboard:
    build: ./scoreboard
    container_name: justitia_scoreboard
    ports:
      - "5000:5000"
    volumes:
      - ./scoreboard/scoreboard.log:/app/scoreboard.log
      - ./scoreboard/scoreboard.json:/app/scoreboard.json
    restart: always
  draw:
    build: ./draw
    container_name: justitia_draw
    ports:
      - "5001:5000"
    volumes:
      - ./draw/data/:/app/data/
    restart: always